[package]
name = "logaddexp"
version = "0.1.1"
edition = "2021"
description = "stable implementations of logaddexp and logsumexp"
repository = "https://github.com/erikbrinkman/logaddexp-rs"
license = "MIT"
keywords = [ "logaddexp", "logsumexp" ]

[dependencies]
num-traits = "0.2"
