name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Install nightly toolchain
      run: rustup toolchain install nightly --component clippy
    - name: Install llvm-tools-preview
      run: rustup component add llvm-tools-preview
    - uses: Swatinem/rust-cache@v2
    - uses: taiki-e/install-action@v2
      with: { tool: cargo-llvm-cov }
    - name: Build
      run: cargo build --verbose
    - name: Run tests with coverage
      run: cargo llvm-cov --verbose --fail-under-lines 90
    - name: Run lints
      run: cargo clippy --verbose --tests -- -D warnings
    - name: Run bench lints
      run: cargo +nightly clippy --verbose --benches -- -D warnings
    - name: Check docs
      run: cargo doc --no-deps
      env:
        RUSTDOCFLAGS: -D warnings
    - name: Check formatting
      run: cargo fmt --verbose --check
